### ISSUE TITLE
wifi sniffer how to compile..

### ISSUE THREAD

**Issue by Patsjemoe** [ESP-EOS/ESP32-WiFi-Sniffer#3]
hi,
you write : 
The sketch shall be compiled with Arduino IDE configured with the proper ESP32 plugin
Can you confirm how this is done.
Do you just copy the .ino file with the rest..or how ?
thanks
regards

**Comment by SalvatoreScalia** [comment]
when the ide uploading, the shell say: " · · · ·_ _ _ · · · ·_ _ _ · · · · ". In this moment press the button BOOT.
First you must have the libraries.
